# Generated by Django 2.2.6 on 2019-12-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191211_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='inactivity_time',
            field=models.IntegerField(default=7, help_text='A message is send to students who have been inactive for the specified number of days.', verbose_name='Days inactive'),
        ),
    ]
