# Generated by Django 2.2.6 on 2019-12-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_inactivity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is this resource called?', max_length=256)),
                ('type', models.CharField(choices=[('book', 'Book'), ('chapter', 'Chapter'), ('lesson', 'Lesson'), ('url', 'Website'), ('resource', 'File'), ('folder', 'Folder'), ('page', 'Page'), ('wiki', 'Wiki')], help_text='What kind of resource is this?', max_length=256)),
                ('target', models.URLField(blank=True, help_text='The link to the content', max_length=256, null=True, verbose_name='Link')),
                ('external', models.BooleanField(default=True, editable=False)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='question',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='contents',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='assignment',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='choice',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='question',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
        migrations.AddField(
            model_name='subject',
            name='resources',
            field=models.ManyToManyField(blank=True, to='courses.Resource'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['target'], name='courses_res_target_0d7e29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('course', 'target')},
        ),
    ]
