# Generated by Django 2.2.6 on 2019-12-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191217_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='target',
            field=models.URLField(blank=True, help_text='The link to the resource', max_length=256, null=True, verbose_name='Link'),
        ),
    ]
