# Generated by Django 2.2.6 on 2020-01-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191217_1016'),
        ('courses', '0004_auto_20191218_1328'),
        ('courses', '0003_auto_20191217_1250'),
    ]

    operations = [
    ]
