# Generated by Django 2.2.6 on 2020-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_merge_20200106_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='external_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='external_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='external_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
