# Generated by Django 2.2.6 on 2020-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200108_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['moodle_id'], name='courses_use_moodle__031829_idx'),
        ),
    ]
