# Generated by Django 2.2.6 on 2020-01-14 10:20

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200108_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='resources',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='course', chained_model_field='course', horizontal=True, to='courses.Resource', verbose_name='resource'),
        ),
    ]
