# Generated by Django 2.2.6 on 2020-01-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200108_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='resources',
        ),
        migrations.AddField(
            model_name='assignment',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Resource'),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='resources',
        ),
        migrations.AddField(
            model_name='choice',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Resource'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='resources',
        ),
        migrations.AddField(
            model_name='question',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Resource'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='resources',
        ),
        migrations.AddField(
            model_name='quiz',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Resource'),
        ),
    ]
