# Generated by Django 2.2.6 on 2020-01-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200113_1305'),
        ('courses', '0007_auto_20200114_1120'),
        ('courses', '0007_auto_20200113_1601'),
    ]

    operations = [
    ]
