# Generated by Django 2.2.6 on 2020-01-20 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0008_merge_20200115_1047'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Role',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('course_id',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                    ],
                    options={
                        'db_table': 'courses_user_courses',
                    },
                ),
                migrations.AlterField(
                    model_name='user',
                    name='courses',
                    field=models.ManyToManyField(through='courses.Role', to='courses.Course'),
                ),
                migrations.AddField(
                    model_name='role',
                    name='user_id',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        )
    ]
