# Generated by Django 2.2.6 on 2020-01-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_role_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('editingteacher', 'teacher'), ('manager', 'manager')], default='editingteacher', max_length=25),
        ),
    ]
