# Generated by Django 2.2.6 on 2019-12-13 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcompletedfeedback',
            name='question_feedback',
            field=models.BooleanField(default=False, verbose_name='Feedback on individual questions'),
        ),
        migrations.AddField(
            model_name='quizcompletedfeedback',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=5.5, help_text='If a student scores below this threshold, he/she will receive feedback.Enter a value between 0 and 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='threshold for quiz feedback'),
        ),
        migrations.DeleteModel(
            name='QuizQuestionFeedback',
        ),
    ]
