# Generated by Django 2.2.6 on 2019-12-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_auto_20191213_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newactivitycreated',
            name='event',
        ),
        migrations.RemoveField(
            model_name='quizcompletedfeedback',
            name='event',
        ),
        migrations.DeleteModel(
            name='SendMessage',
        ),
    ]
