# Generated by Django 2.2.6 on 2020-01-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_auto_20191219_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newactivitycreated',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='quizcompletedfeedback',
            name='destination',
        ),
    ]
