# Generated by Django 2.2.6 on 2020-01-13 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_auto_20191219_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcompletedfeedback',
            name='threshold',
            field=models.IntegerField(default=55, help_text='If a student scores below this threshold, he/she will receive feedback.Enter a value between 0 and 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='threshold for quiz feedback'),
        ),
    ]
