# Generated by Django 2.2.6 on 2020-01-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0004_auto_20200113_1333'),
        ('assistants', '0004_auto_20200113_1046'),
    ]

    operations = [
    ]
