# Generated by Django 2.2.6 on 2020-01-15 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0005_merge_20200114_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcompletedfeedback',
            name='quiz',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, to='courses.Quiz'),
        ),
        migrations.AlterField(
            model_name='quizcompletedfeedback',
            name='threshold',
            field=models.IntegerField(default=55, help_text='If a student scores below this threshold, he/she will receive feedback. Enter a value between 0 and 100. The score is in percentages.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='threshold for quiz feedback'),
        ),
    ]
