# Generated by Django 2.2.6 on 2020-01-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200120_1451'),
        ('assistants', '0006_auto_20200115_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwarder_id', models.CharField(default=0, max_length=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
