# Generated by Django 2.2.6 on 2020-01-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0007_dummyassistant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyAssistant',
        ),
    ]
