name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repo
    
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.1'
        
    - name: Check PHP Version
      working-directory: docker/xapi
      run: php -v
        
    - name: Validate composer.json and composer.lock
      working-directory: docker/xapi
      run: composer validate

    - name: Install dependencies
      working-directory: docker/xapi
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      working-directory: docker/xapi
      run: composer run-script test
